### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by 508hz1207** [suniique/Leveraging-Crowdsourced-GPS-Data-for-Road-Extraction-from-Aerial-Imagery#4]
您好作者，我是一名武大做路网提取的研究生，读了您的文章，深受启发，可不可以共享下您本篇文章遥感影像与轨迹原始数据，我的邮箱是zjwang@whu.edu.cn 本人将不胜感激。

**Comment by suniique** [comment]
Sent to your email!
